name: dart_anchor_link
description: Persistent sessions that allows applications to setup a persistent and secure channel for pushing signature requests (ESR/EEP-7) to a wallet.
version: 0.0.0
homepage: https://github.com/TheRealPaco/dart-anchor-link

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:  
  web_socket_channel: ^1.1.0
  pointycastle: ^1.0.2
  uuid: ^2.2.0
  eosdart_ecc: ^0.4.3
  eosdart:
    git: 
      url: https://github.com/TheRealPaco/eosdart.git
  dart_esr:
    git:
      url: https://github.com/EOS-Nation/dart-esr
      ref: feature/complete-port-of-esr-js
      
dev_dependencies:
  test: ^1.0.0